changelog:
  categories:
    - title: "🚀 Features"
      labels:
        - "enhancement"
        - "feature"
    - title: "🐛 Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "📦 Dependencies"
      labels:
        - "dependencies"
        - "automated"
    - title: "🔧 Maintenance"
      labels:
        - "chore"
        - "maintenance"
    - title: "📝 Documentation"
      labels:
        - "documentation"
        - "docs"
    - title: "Other Changes"
      labels:
        - "*"
